int8 cmd_id	        # 1:Add , 2:modify 3:delete 4:requery 		
string index_name 
string parameter 	
robot_ctrl_roslog rec_roslog	 
---
bool result
string error_code
robot_ctrl_roslog[] result_roslogs	 
