; Auto-generated. Do not edit!


(cl:in-package samsungcmd_msgs-msg)


;//! \htmlinclude samsung_commdata_actFeedback.msg.html

(cl:defclass <samsung_commdata_actFeedback> (roslisp-msg-protocol:ros-message)
  ((status_id
    :reader status_id
    :initarg :status_id
    :type cl:fixnum
    :initform 0)
   (status_desc
    :reader status_desc
    :initarg :status_desc
    :type cl:string
    :initform ""))
)

(cl:defclass samsung_commdata_actFeedback (<samsung_commdata_actFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <samsung_commdata_actFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'samsung_commdata_actFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name samsungcmd_msgs-msg:<samsung_commdata_actFeedback> is deprecated: use samsungcmd_msgs-msg:samsung_commdata_actFeedback instead.")))

(cl:ensure-generic-function 'status_id-val :lambda-list '(m))
(cl:defmethod status_id-val ((m <samsung_commdata_actFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader samsungcmd_msgs-msg:status_id-val is deprecated.  Use samsungcmd_msgs-msg:status_id instead.")
  (status_id m))

(cl:ensure-generic-function 'status_desc-val :lambda-list '(m))
(cl:defmethod status_desc-val ((m <samsung_commdata_actFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader samsungcmd_msgs-msg:status_desc-val is deprecated.  Use samsungcmd_msgs-msg:status_desc instead.")
  (status_desc m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <samsung_commdata_actFeedback>) ostream)
  "Serializes a message object of type '<samsung_commdata_actFeedback>"
  (cl:let* ((signed (cl:slot-value msg 'status_id)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 256) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    )
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'status_desc))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'status_desc))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <samsung_commdata_actFeedback>) istream)
  "Deserializes a message object of type '<samsung_commdata_actFeedback>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'status_id) (cl:if (cl:< unsigned 128) unsigned (cl:- unsigned 256))))
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'status_desc) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'status_desc) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<samsung_commdata_actFeedback>)))
  "Returns string type for a message object of type '<samsung_commdata_actFeedback>"
  "samsungcmd_msgs/samsung_commdata_actFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'samsung_commdata_actFeedback)))
  "Returns string type for a message object of type 'samsung_commdata_actFeedback"
  "samsungcmd_msgs/samsung_commdata_actFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<samsung_commdata_actFeedback>)))
  "Returns md5sum for a message object of type '<samsung_commdata_actFeedback>"
  "8477dd7d5143d4c2230befe0e46a82e2")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'samsung_commdata_actFeedback)))
  "Returns md5sum for a message object of type 'samsung_commdata_actFeedback"
  "8477dd7d5143d4c2230befe0e46a82e2")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<samsung_commdata_actFeedback>)))
  "Returns full string definition for message of type '<samsung_commdata_actFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Feedback~%int8    status_id~%string  status_desc~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'samsung_commdata_actFeedback)))
  "Returns full string definition for message of type 'samsung_commdata_actFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Feedback~%int8    status_id~%string  status_desc~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <samsung_commdata_actFeedback>))
  (cl:+ 0
     1
     4 (cl:length (cl:slot-value msg 'status_desc))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <samsung_commdata_actFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'samsung_commdata_actFeedback
    (cl:cons ':status_id (status_id msg))
    (cl:cons ':status_desc (status_desc msg))
))
