(cl:in-package robot_control_msgs-msg)
(cl:export '(HEADER-VAL
          HEADER
          ROBOT_NAME-VAL
          ROBOT_NAME
          POSE-VAL
          POSE
          CURRENT_ROUTE_SEGMENT-VAL
          CURRENT_ROUTE_SEGMENT
          SHAPE-VAL
          SHAPE
          SHAPE_VARIABLES-VAL
          SHAPE_VARIABLES
          HANDLER_TYPE-VAL
          HANDLER_TYPE
          BATTERY_ID-VAL
          BATTERY_ID
          BATTERY_CAPACITY-VAL
          BATTERY_CAPACITY
          BATTERY_CHARGETIME-VAL
          BATTERY_CHARGETIME
          BATTERY_SERVICETIME-VAL
          BATTERY_SERVICETIME
          MODE-VAL
          MODE
          STATUS-VAL
          STATUS
          ERROR_CODE-VAL
          ERROR_CODE
          GOOD_ID-VAL
          GOOD_ID
          ORDER_ID-VAL
          ORDER_ID
          ORDER_STATUS-VAL
          ORDER_STATUS
))