int8 cmd_id         # 1:Add , 2:modify , 3:delete , 4:requery , 5:refresh	 		
string query_base_index 	
string query_opt_index
string query_parameter 
CarAlarmHistory req_car_alarm_history
---
bool result
string error_code
string primary_id
string update_time
CarAlarmHistory[] result_car_alarm_history
