// Generated by gencpp from file samsungcmd_msgs/samsung_iosequence_actGoal.msg
// DO NOT EDIT!


#ifndef SAMSUNGCMD_MSGS_MESSAGE_SAMSUNG_IOSEQUENCE_ACTGOAL_H
#define SAMSUNGCMD_MSGS_MESSAGE_SAMSUNG_IOSEQUENCE_ACTGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace samsungcmd_msgs
{
template <class ContainerAllocator>
struct samsung_iosequence_actGoal_
{
  typedef samsung_iosequence_actGoal_<ContainerAllocator> Type;

  samsung_iosequence_actGoal_()
    : seq_start(false)
    , seq_functionNo(0)  {
    }
  samsung_iosequence_actGoal_(const ContainerAllocator& _alloc)
    : seq_start(false)
    , seq_functionNo(0)  {
  (void)_alloc;
    }



   typedef uint8_t _seq_start_type;
  _seq_start_type seq_start;

   typedef int8_t _seq_functionNo_type;
  _seq_functionNo_type seq_functionNo;





  typedef boost::shared_ptr< ::samsungcmd_msgs::samsung_iosequence_actGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::samsungcmd_msgs::samsung_iosequence_actGoal_<ContainerAllocator> const> ConstPtr;

}; // struct samsung_iosequence_actGoal_

typedef ::samsungcmd_msgs::samsung_iosequence_actGoal_<std::allocator<void> > samsung_iosequence_actGoal;

typedef boost::shared_ptr< ::samsungcmd_msgs::samsung_iosequence_actGoal > samsung_iosequence_actGoalPtr;
typedef boost::shared_ptr< ::samsungcmd_msgs::samsung_iosequence_actGoal const> samsung_iosequence_actGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::samsungcmd_msgs::samsung_iosequence_actGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::samsungcmd_msgs::samsung_iosequence_actGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::samsungcmd_msgs::samsung_iosequence_actGoal_<ContainerAllocator1> & lhs, const ::samsungcmd_msgs::samsung_iosequence_actGoal_<ContainerAllocator2> & rhs)
{
  return lhs.seq_start == rhs.seq_start &&
    lhs.seq_functionNo == rhs.seq_functionNo;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::samsungcmd_msgs::samsung_iosequence_actGoal_<ContainerAllocator1> & lhs, const ::samsungcmd_msgs::samsung_iosequence_actGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace samsungcmd_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::samsungcmd_msgs::samsung_iosequence_actGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::samsungcmd_msgs::samsung_iosequence_actGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::samsungcmd_msgs::samsung_iosequence_actGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::samsungcmd_msgs::samsung_iosequence_actGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::samsungcmd_msgs::samsung_iosequence_actGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::samsungcmd_msgs::samsung_iosequence_actGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::samsungcmd_msgs::samsung_iosequence_actGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bee0d5b65d6ab542f2eb9e4ac13d2f1c";
  }

  static const char* value(const ::samsungcmd_msgs::samsung_iosequence_actGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbee0d5b65d6ab542ULL;
  static const uint64_t static_value2 = 0xf2eb9e4ac13d2f1cULL;
};

template<class ContainerAllocator>
struct DataType< ::samsungcmd_msgs::samsung_iosequence_actGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "samsungcmd_msgs/samsung_iosequence_actGoal";
  }

  static const char* value(const ::samsungcmd_msgs::samsung_iosequence_actGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::samsungcmd_msgs::samsung_iosequence_actGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Goal\n"
"bool  	seq_start\n"
"int8  	seq_functionNo\n"
;
  }

  static const char* value(const ::samsungcmd_msgs::samsung_iosequence_actGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::samsungcmd_msgs::samsung_iosequence_actGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.seq_start);
      stream.next(m.seq_functionNo);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct samsung_iosequence_actGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::samsungcmd_msgs::samsung_iosequence_actGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::samsungcmd_msgs::samsung_iosequence_actGoal_<ContainerAllocator>& v)
  {
    s << indent << "seq_start: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.seq_start);
    s << indent << "seq_functionNo: ";
    Printer<int8_t>::stream(s, indent + "  ", v.seq_functionNo);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SAMSUNGCMD_MSGS_MESSAGE_SAMSUNG_IOSEQUENCE_ACTGOAL_H
