// Generated by gencpp from file samsungcmd_msgs/samsung_commdata_actGoal.msg
// DO NOT EDIT!


#ifndef SAMSUNGCMD_MSGS_MESSAGE_SAMSUNG_COMMDATA_ACTGOAL_H
#define SAMSUNGCMD_MSGS_MESSAGE_SAMSUNG_COMMDATA_ACTGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace samsungcmd_msgs
{
template <class ContainerAllocator>
struct samsung_commdata_actGoal_
{
  typedef samsung_commdata_actGoal_<ContainerAllocator> Type;

  samsung_commdata_actGoal_()
    : b_cruise(false)
    , car_ID()  {
    }
  samsung_commdata_actGoal_(const ContainerAllocator& _alloc)
    : b_cruise(false)
    , car_ID(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _b_cruise_type;
  _b_cruise_type b_cruise;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _car_ID_type;
  _car_ID_type car_ID;





  typedef boost::shared_ptr< ::samsungcmd_msgs::samsung_commdata_actGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::samsungcmd_msgs::samsung_commdata_actGoal_<ContainerAllocator> const> ConstPtr;

}; // struct samsung_commdata_actGoal_

typedef ::samsungcmd_msgs::samsung_commdata_actGoal_<std::allocator<void> > samsung_commdata_actGoal;

typedef boost::shared_ptr< ::samsungcmd_msgs::samsung_commdata_actGoal > samsung_commdata_actGoalPtr;
typedef boost::shared_ptr< ::samsungcmd_msgs::samsung_commdata_actGoal const> samsung_commdata_actGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::samsungcmd_msgs::samsung_commdata_actGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::samsungcmd_msgs::samsung_commdata_actGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::samsungcmd_msgs::samsung_commdata_actGoal_<ContainerAllocator1> & lhs, const ::samsungcmd_msgs::samsung_commdata_actGoal_<ContainerAllocator2> & rhs)
{
  return lhs.b_cruise == rhs.b_cruise &&
    lhs.car_ID == rhs.car_ID;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::samsungcmd_msgs::samsung_commdata_actGoal_<ContainerAllocator1> & lhs, const ::samsungcmd_msgs::samsung_commdata_actGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace samsungcmd_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::samsungcmd_msgs::samsung_commdata_actGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::samsungcmd_msgs::samsung_commdata_actGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::samsungcmd_msgs::samsung_commdata_actGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::samsungcmd_msgs::samsung_commdata_actGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::samsungcmd_msgs::samsung_commdata_actGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::samsungcmd_msgs::samsung_commdata_actGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::samsungcmd_msgs::samsung_commdata_actGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6c727684f39f0efc1886eb7f69f727f7";
  }

  static const char* value(const ::samsungcmd_msgs::samsung_commdata_actGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6c727684f39f0efcULL;
  static const uint64_t static_value2 = 0x1886eb7f69f727f7ULL;
};

template<class ContainerAllocator>
struct DataType< ::samsungcmd_msgs::samsung_commdata_actGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "samsungcmd_msgs/samsung_commdata_actGoal";
  }

  static const char* value(const ::samsungcmd_msgs::samsung_commdata_actGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::samsungcmd_msgs::samsung_commdata_actGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Goal\n"
"bool  	b_cruise\n"
"string  car_ID\n"
;
  }

  static const char* value(const ::samsungcmd_msgs::samsung_commdata_actGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::samsungcmd_msgs::samsung_commdata_actGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.b_cruise);
      stream.next(m.car_ID);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct samsung_commdata_actGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::samsungcmd_msgs::samsung_commdata_actGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::samsungcmd_msgs::samsung_commdata_actGoal_<ContainerAllocator>& v)
  {
    s << indent << "b_cruise: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.b_cruise);
    s << indent << "car_ID: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.car_ID);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SAMSUNGCMD_MSGS_MESSAGE_SAMSUNG_COMMDATA_ACTGOAL_H
