; Auto-generated. Do not edit!


(cl:in-package robot_scheduling_msgs-msg)


;//! \htmlinclude db_process_recoveryFeedback.msg.html

(cl:defclass <db_process_recoveryFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass db_process_recoveryFeedback (<db_process_recoveryFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <db_process_recoveryFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'db_process_recoveryFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name robot_scheduling_msgs-msg:<db_process_recoveryFeedback> is deprecated: use robot_scheduling_msgs-msg:db_process_recoveryFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <db_process_recoveryFeedback>) ostream)
  "Serializes a message object of type '<db_process_recoveryFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <db_process_recoveryFeedback>) istream)
  "Deserializes a message object of type '<db_process_recoveryFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<db_process_recoveryFeedback>)))
  "Returns string type for a message object of type '<db_process_recoveryFeedback>"
  "robot_scheduling_msgs/db_process_recoveryFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'db_process_recoveryFeedback)))
  "Returns string type for a message object of type 'db_process_recoveryFeedback"
  "robot_scheduling_msgs/db_process_recoveryFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<db_process_recoveryFeedback>)))
  "Returns md5sum for a message object of type '<db_process_recoveryFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'db_process_recoveryFeedback)))
  "Returns md5sum for a message object of type 'db_process_recoveryFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<db_process_recoveryFeedback>)))
  "Returns full string definition for message of type '<db_process_recoveryFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define a feedback message~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'db_process_recoveryFeedback)))
  "Returns full string definition for message of type 'db_process_recoveryFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define a feedback message~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <db_process_recoveryFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <db_process_recoveryFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'db_process_recoveryFeedback
))
