; Auto-generated. Do not edit!


(cl:in-package robot_scheduling_msgs-msg)


;//! \htmlinclude pose_recognize_recoveryGoal.msg.html

(cl:defclass <pose_recognize_recoveryGoal> (roslisp-msg-protocol:ros-message)
  ((turn_ac_name
    :reader turn_ac_name
    :initarg :turn_ac_name
    :type cl:string
    :initform ""))
)

(cl:defclass pose_recognize_recoveryGoal (<pose_recognize_recoveryGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <pose_recognize_recoveryGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'pose_recognize_recoveryGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name robot_scheduling_msgs-msg:<pose_recognize_recoveryGoal> is deprecated: use robot_scheduling_msgs-msg:pose_recognize_recoveryGoal instead.")))

(cl:ensure-generic-function 'turn_ac_name-val :lambda-list '(m))
(cl:defmethod turn_ac_name-val ((m <pose_recognize_recoveryGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader robot_scheduling_msgs-msg:turn_ac_name-val is deprecated.  Use robot_scheduling_msgs-msg:turn_ac_name instead.")
  (turn_ac_name m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <pose_recognize_recoveryGoal>) ostream)
  "Serializes a message object of type '<pose_recognize_recoveryGoal>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'turn_ac_name))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'turn_ac_name))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <pose_recognize_recoveryGoal>) istream)
  "Deserializes a message object of type '<pose_recognize_recoveryGoal>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'turn_ac_name) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'turn_ac_name) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<pose_recognize_recoveryGoal>)))
  "Returns string type for a message object of type '<pose_recognize_recoveryGoal>"
  "robot_scheduling_msgs/pose_recognize_recoveryGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'pose_recognize_recoveryGoal)))
  "Returns string type for a message object of type 'pose_recognize_recoveryGoal"
  "robot_scheduling_msgs/pose_recognize_recoveryGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<pose_recognize_recoveryGoal>)))
  "Returns md5sum for a message object of type '<pose_recognize_recoveryGoal>"
  "28e9dc391c5817e192aeacf5bd0c99f3")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'pose_recognize_recoveryGoal)))
  "Returns md5sum for a message object of type 'pose_recognize_recoveryGoal"
  "28e9dc391c5817e192aeacf5bd0c99f3")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<pose_recognize_recoveryGoal>)))
  "Returns full string definition for message of type '<pose_recognize_recoveryGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the goal~%string turn_ac_name~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'pose_recognize_recoveryGoal)))
  "Returns full string definition for message of type 'pose_recognize_recoveryGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the goal~%string turn_ac_name~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <pose_recognize_recoveryGoal>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'turn_ac_name))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <pose_recognize_recoveryGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'pose_recognize_recoveryGoal
    (cl:cons ':turn_ac_name (turn_ac_name msg))
))
