; Auto-generated. Do not edit!


(cl:in-package robot_scheduling_msgs-msg)


;//! \htmlinclude robot_commandGoal.msg.html

(cl:defclass <robot_commandGoal> (roslisp-msg-protocol:ros-message)
  ((command
    :reader command
    :initarg :command
    :type cl:fixnum
    :initform 0)
   (set_status
    :reader set_status
    :initarg :set_status
    :type cl:fixnum
    :initform 0))
)

(cl:defclass robot_commandGoal (<robot_commandGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <robot_commandGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'robot_commandGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name robot_scheduling_msgs-msg:<robot_commandGoal> is deprecated: use robot_scheduling_msgs-msg:robot_commandGoal instead.")))

(cl:ensure-generic-function 'command-val :lambda-list '(m))
(cl:defmethod command-val ((m <robot_commandGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader robot_scheduling_msgs-msg:command-val is deprecated.  Use robot_scheduling_msgs-msg:command instead.")
  (command m))

(cl:ensure-generic-function 'set_status-val :lambda-list '(m))
(cl:defmethod set_status-val ((m <robot_commandGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader robot_scheduling_msgs-msg:set_status-val is deprecated.  Use robot_scheduling_msgs-msg:set_status instead.")
  (set_status m))
(cl:defmethod roslisp-msg-protocol:symbol-codes ((msg-type (cl:eql '<robot_commandGoal>)))
    "Constants for message type '<robot_commandGoal>"
  '((:GET . 1)
    (:SET . 2)
    (:DISPATCH . 3)
    (:UNKNOW . 1)
    (:INIT_POSE . 2)
    (:STANDBY . 3)
    (:MANU_RUN . 4)
    (:REMOTE . 5)
    (:ALARM . 6)
    (:EXIT . 7))
)
(cl:defmethod roslisp-msg-protocol:symbol-codes ((msg-type (cl:eql 'robot_commandGoal)))
    "Constants for message type 'robot_commandGoal"
  '((:GET . 1)
    (:SET . 2)
    (:DISPATCH . 3)
    (:UNKNOW . 1)
    (:INIT_POSE . 2)
    (:STANDBY . 3)
    (:MANU_RUN . 4)
    (:REMOTE . 5)
    (:ALARM . 6)
    (:EXIT . 7))
)
(cl:defmethod roslisp-msg-protocol:serialize ((msg <robot_commandGoal>) ostream)
  "Serializes a message object of type '<robot_commandGoal>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'command)) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'set_status)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <robot_commandGoal>) istream)
  "Deserializes a message object of type '<robot_commandGoal>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'command)) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'set_status)) (cl:read-byte istream))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<robot_commandGoal>)))
  "Returns string type for a message object of type '<robot_commandGoal>"
  "robot_scheduling_msgs/robot_commandGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'robot_commandGoal)))
  "Returns string type for a message object of type 'robot_commandGoal"
  "robot_scheduling_msgs/robot_commandGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<robot_commandGoal>)))
  "Returns md5sum for a message object of type '<robot_commandGoal>"
  "b28059bb37d56347b09d592634a664fe")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'robot_commandGoal)))
  "Returns md5sum for a message object of type 'robot_commandGoal"
  "b28059bb37d56347b09d592634a664fe")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<robot_commandGoal>)))
  "Returns full string definition for message of type '<robot_commandGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the goal~%uint8 GET=1~%uint8 SET=2~%uint8 DISPATCH =3~%uint8 command~%uint8 UNKNOW=1~%uint8 INIT_POSE=2~%uint8 STANDBY=3~%uint8 MANU_RUN=4~%uint8 REMOTE=5~%uint8 ALARM=6~%uint8 EXIT=7~%uint8 set_status~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'robot_commandGoal)))
  "Returns full string definition for message of type 'robot_commandGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define the goal~%uint8 GET=1~%uint8 SET=2~%uint8 DISPATCH =3~%uint8 command~%uint8 UNKNOW=1~%uint8 INIT_POSE=2~%uint8 STANDBY=3~%uint8 MANU_RUN=4~%uint8 REMOTE=5~%uint8 ALARM=6~%uint8 EXIT=7~%uint8 set_status~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <robot_commandGoal>))
  (cl:+ 0
     1
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <robot_commandGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'robot_commandGoal
    (cl:cons ':command (command msg))
    (cl:cons ':set_status (set_status msg))
))
