// Auto-generated. Do not edit!

// (in-package actionlib_modules_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;
let locomotor_msgs = _finder('locomotor_msgs');

//-----------------------------------------------------------

class actionlib_agv_movetoResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.result = null;
      this.result_code = null;
    }
    else {
      if (initObj.hasOwnProperty('result')) {
        this.result = initObj.result
      }
      else {
        this.result = 0;
      }
      if (initObj.hasOwnProperty('result_code')) {
        this.result_code = initObj.result_code
      }
      else {
        this.result_code = new locomotor_msgs.msg.ResultCode();
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type actionlib_agv_movetoResult
    // Serialize message field [result]
    bufferOffset = _serializer.uint8(obj.result, buffer, bufferOffset);
    // Serialize message field [result_code]
    bufferOffset = locomotor_msgs.msg.ResultCode.serialize(obj.result_code, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type actionlib_agv_movetoResult
    let len;
    let data = new actionlib_agv_movetoResult(null);
    // Deserialize message field [result]
    data.result = _deserializer.uint8(buffer, bufferOffset);
    // Deserialize message field [result_code]
    data.result_code = locomotor_msgs.msg.ResultCode.deserialize(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += locomotor_msgs.msg.ResultCode.getMessageSize(object.result_code);
    return length + 1;
  }

  static datatype() {
    // Returns string type for a message object
    return 'actionlib_modules_msgs/actionlib_agv_movetoResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'e2274c42394ce6b5fa678d84f0f7eed0';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Define the result
    uint8 OK=1
    uint8 NOT_OK=2
    uint8 TIMED_OUT=3
    uint8 result
    locomotor_msgs/ResultCode result_code
    
    ================================================================================
    MSG: locomotor_msgs/ResultCode
    # This message contains three separate pieces.
    #    A) A code indicating which component(s) the error originates from (bitmask style)
    #    B) A code corresponding with the result_code defined in nav_core2/s.h
    #    C) A freeform string message
    
    # The enumerations below are not necessarily the exclusive values for the codes.
    # Others may implement additional values beyond the ones shown, using custom state machines.
    
    ########### Component Values ###############################################
    int32 GLOBAL_COSTMAP = 1
    int32  LOCAL_COSTMAP = 2
    int32 GLOBAL_PLANNER = 4
    int32  LOCAL_PLANNER = 8
    
    ########### Result Codes ###################################################
    int32 GENERIC_COSTMAP=0
    int32 COSTMAP_SAFETY=1
    int32 COSTMAP_DATA_LAG=2
    int32 GENERIC_PLANNER=3
    int32 GENERIC_GLOBAL_PLANNER=4
    int32 INVALID_START=5
    int32 START_BOUNDS=6
    int32 OCCUPIED_START=7
    int32 INVALID_GOAL=8
    int32 GOAL_BOUNDS=9
    int32 OCCUPIED_GOAL=10
    int32 NO_GLOBAL_PATH=11
    int32 GLOBAL_PLANNER_TIMEOUT=12
    int32 GENERIC_LOCAL_PLANNER=13
    int32 ILLEGAL_TRAJECTORY=14
    int32 NO_LEGAL_TRAJECTORIES=15
    int32 PLANNER_TF=16
    
    ########### Actual Data ####################################################
    int32 component
    int32 result_code
    string message
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new actionlib_agv_movetoResult(null);
    if (msg.result !== undefined) {
      resolved.result = msg.result;
    }
    else {
      resolved.result = 0
    }

    if (msg.result_code !== undefined) {
      resolved.result_code = locomotor_msgs.msg.ResultCode.Resolve(msg.result_code)
    }
    else {
      resolved.result_code = new locomotor_msgs.msg.ResultCode()
    }

    return resolved;
    }
};

// Constants for message
actionlib_agv_movetoResult.Constants = {
  OK: 1,
  NOT_OK: 2,
  TIMED_OUT: 3,
}

module.exports = actionlib_agv_movetoResult;
