string 	key_id
uint16  station_id
uint8 	station_type		# 0: sAnti-collision/1:direction-id
uint16 	delay_time		    # 0: - /1:keep time for straight-run
uint16 	timeout_value  		# 0: no respone for sAnti-collision/ 1:check out codition of turn	
uint16 	start_turn_right 	# 0: - /1:range start for turn-right	
uint16 	end_turn_right 		# 0: - /1:range end for turn-right
uint16 	start_straight 		# 0: - /1:range start for straight	
uint16 	end_straight 		# 0: - /1:range end for straight
uint16 	start_turn_left 	# 0: - /1:range start for turn-left	
uint16 	end_turn_left 		# 0: - /1:range end for turn-left
string 	update_time
