string primary_id			# must-have,UUID : primary_key(system_id)
string unique_code 		        # must-have,UNIQUE INDEX	
string agv_standtype		   
string agv_model_no 		 
string agv_name 		 
uint8  agv_shape 	
float32 agv_shape_para0 
float32 agv_shape_para1 
float32 agv_shape_para2 	
uint8  agv_candidate 
uint8  agv_transfer_type
string put_in_service_date
float32 work_comulative_time
uint8 current_status
string update_time			# must-have 	 
