string primary_id			# must-have,UUID : primary_key(system_id)
string unique_code 		        # must-have,UNIQUE INDEX	
string station_name		   
string cellcontroller_code 		 
geometry_msgs/Pose positioned_pose 		 
uint8  mc_func_code 	
uint8  transfer_code 	
uint8  transfer_state 
uint8  align_type
string align_metadata
geometry_msgs/Pose pre_positioned_pose
string Identify_id
string update_time			# must-have 	 
