int8 cmd_id         # 1:Add , 2:modify , 3:delete , 4:requery , 5:refresh	 		
string query_base_index 	
string query_opt_index
string query_parameter 
base_cell_controller req_base_cellcontroller	 
---
bool result
string error_code
string primary_id
string update_time
base_cell_controller[] result_base_cellcontroller
