(cl:in-package cellctrl_control_msgs-msg)
(cl:export '(PRIMARY_ID-VAL
          PRIMARY_ID
          UNIQUE_CODE-VAL
          UNIQUE_CODE
          AGV_STANDTYPE-VAL
          AGV_STANDTYPE
          AGV_MODEL_NO-VAL
          AGV_MODEL_NO
          AGV_NAME-VAL
          AGV_NAME
          AGV_SHAPE-VAL
          AGV_SHAPE
          AGV_SHAPE_PARA0-VAL
          AGV_SHAPE_PARA0
          AGV_SHAPE_PARA1-VAL
          AGV_SHAPE_PARA1
          AGV_SHAPE_PARA2-VAL
          AGV_SHAPE_PARA2
          AGV_CANDIDATE-VAL
          AGV_CANDIDATE
          AGV_TRANSFER_TYPE-VAL
          AGV_TRANSFER_TYPE
          PUT_IN_SERVICE_DATE-VAL
          PUT_IN_SERVICE_DATE
          WORK_COMULATIVE_TIME-VAL
          WORK_COMULATIVE_TIME
          CURRENT_STATUS-VAL
          CURRENT_STATUS
          UPDATE_TIME-VAL
          UPDATE_TIME
))