(cl:in-package cellctrl_control_msgs-msg)
(cl:export '(PRIMARY_ID-VAL
          PRIMARY_ID
          FOREIGN_KEY-VAL
          FOREIGN_KEY
          UNIQUE_CODE-VAL
          UNIQUE_CODE
          STATION_NAME-VAL
          STATION_NAME
          STATION_SER-VAL
          STATION_SER
          CELLCONTROLLER_CODE-VAL
          CELLCONTROLLER_CODE
          POSITIONED_POSE-VAL
          POSITIONED_POSE
          MC_FUNC_CODE-VAL
          MC_FUNC_CODE
          TRANSFER_CODE-VAL
          TRANSFER_CODE
          TRANSFER_STATE-VAL
          TRANSFER_STATE
          ALIGN_TYPE-VAL
          ALIGN_TYPE
          ALIGN_METADATA-VAL
          ALIGN_METADATA
          PRE_POSITIONED_POSE-VAL
          PRE_POSITIONED_POSE
          IDENTIFY_ID-VAL
          IDENTIFY_ID
          UPDATE_TIME-VAL
          UPDATE_TIME
))