(cl:defpackage reset_location-msg
  (:use )
  (:export
   "<TRILATERATIONACTION>"
   "TRILATERATIONACTION"
   "<TRILATERATIONACTIONFEEDBACK>"
   "TRILATERATIONACTIONFEEDBACK"
   "<TRILATERATIONACTIONGOAL>"
   "TRILATERATIONACTIONGOAL"
   "<TRILATERATIONACTIONRESULT>"
   "TRILATERATIONACTIONRESULT"
   "<TRILATERATIONFEEDBACK>"
   "TRILATERATIONFEEDBACK"
   "<TRILATERATIONGOAL>"
   "TRILATERATIONGOAL"
   "<TRILATERATIONRESULT>"
   "TRILATERATIONRESULT"
  ))

