// Generated by gencpp from file botcmd_msgs/bot_di_cmd.msg
// DO NOT EDIT!


#ifndef BOTCMD_MSGS_MESSAGE_BOT_DI_CMD_H
#define BOTCMD_MSGS_MESSAGE_BOT_DI_CMD_H

#include <ros/service_traits.h>


#include <botcmd_msgs/bot_di_cmdRequest.h>
#include <botcmd_msgs/bot_di_cmdResponse.h>


namespace botcmd_msgs
{

struct bot_di_cmd
{

typedef bot_di_cmdRequest Request;
typedef bot_di_cmdResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct bot_di_cmd
} // namespace botcmd_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::botcmd_msgs::bot_di_cmd > {
  static const char* value()
  {
    return "1370eea95d2e64a2a473cf48bbf54676";
  }

  static const char* value(const ::botcmd_msgs::bot_di_cmd&) { return value(); }
};

template<>
struct DataType< ::botcmd_msgs::bot_di_cmd > {
  static const char* value()
  {
    return "botcmd_msgs/bot_di_cmd";
  }

  static const char* value(const ::botcmd_msgs::bot_di_cmd&) { return value(); }
};


// service_traits::MD5Sum< ::botcmd_msgs::bot_di_cmdRequest> should match
// service_traits::MD5Sum< ::botcmd_msgs::bot_di_cmd >
template<>
struct MD5Sum< ::botcmd_msgs::bot_di_cmdRequest>
{
  static const char* value()
  {
    return MD5Sum< ::botcmd_msgs::bot_di_cmd >::value();
  }
  static const char* value(const ::botcmd_msgs::bot_di_cmdRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::botcmd_msgs::bot_di_cmdRequest> should match
// service_traits::DataType< ::botcmd_msgs::bot_di_cmd >
template<>
struct DataType< ::botcmd_msgs::bot_di_cmdRequest>
{
  static const char* value()
  {
    return DataType< ::botcmd_msgs::bot_di_cmd >::value();
  }
  static const char* value(const ::botcmd_msgs::bot_di_cmdRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::botcmd_msgs::bot_di_cmdResponse> should match
// service_traits::MD5Sum< ::botcmd_msgs::bot_di_cmd >
template<>
struct MD5Sum< ::botcmd_msgs::bot_di_cmdResponse>
{
  static const char* value()
  {
    return MD5Sum< ::botcmd_msgs::bot_di_cmd >::value();
  }
  static const char* value(const ::botcmd_msgs::bot_di_cmdResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::botcmd_msgs::bot_di_cmdResponse> should match
// service_traits::DataType< ::botcmd_msgs::bot_di_cmd >
template<>
struct DataType< ::botcmd_msgs::bot_di_cmdResponse>
{
  static const char* value()
  {
    return DataType< ::botcmd_msgs::bot_di_cmd >::value();
  }
  static const char* value(const ::botcmd_msgs::bot_di_cmdResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BOTCMD_MSGS_MESSAGE_BOT_DI_CMD_H
