// Generated by gencpp from file botcmd_msgs/bot_status_cmdResponse.msg
// DO NOT EDIT!


#ifndef BOTCMD_MSGS_MESSAGE_BOT_STATUS_CMDRESPONSE_H
#define BOTCMD_MSGS_MESSAGE_BOT_STATUS_CMDRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace botcmd_msgs
{
template <class ContainerAllocator>
struct bot_status_cmdResponse_
{
  typedef bot_status_cmdResponse_<ContainerAllocator> Type;

  bot_status_cmdResponse_()
    : result(false)
    , stamp()
    , result_Command(0)
    , status_code(0)
    , error_code(0)
    , data()  {
    }
  bot_status_cmdResponse_(const ContainerAllocator& _alloc)
    : result(false)
    , stamp()
    , result_Command(0)
    , status_code(0)
    , error_code(0)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _result_type;
  _result_type result;

   typedef ros::Time _stamp_type;
  _stamp_type stamp;

   typedef int16_t _result_Command_type;
  _result_Command_type result_Command;

   typedef int8_t _status_code_type;
  _status_code_type status_code;

   typedef int8_t _error_code_type;
  _error_code_type error_code;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::botcmd_msgs::bot_status_cmdResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::botcmd_msgs::bot_status_cmdResponse_<ContainerAllocator> const> ConstPtr;

}; // struct bot_status_cmdResponse_

typedef ::botcmd_msgs::bot_status_cmdResponse_<std::allocator<void> > bot_status_cmdResponse;

typedef boost::shared_ptr< ::botcmd_msgs::bot_status_cmdResponse > bot_status_cmdResponsePtr;
typedef boost::shared_ptr< ::botcmd_msgs::bot_status_cmdResponse const> bot_status_cmdResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::botcmd_msgs::bot_status_cmdResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::botcmd_msgs::bot_status_cmdResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::botcmd_msgs::bot_status_cmdResponse_<ContainerAllocator1> & lhs, const ::botcmd_msgs::bot_status_cmdResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result &&
    lhs.stamp == rhs.stamp &&
    lhs.result_Command == rhs.result_Command &&
    lhs.status_code == rhs.status_code &&
    lhs.error_code == rhs.error_code &&
    lhs.data == rhs.data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::botcmd_msgs::bot_status_cmdResponse_<ContainerAllocator1> & lhs, const ::botcmd_msgs::bot_status_cmdResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace botcmd_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::botcmd_msgs::bot_status_cmdResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::botcmd_msgs::bot_status_cmdResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::botcmd_msgs::bot_status_cmdResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::botcmd_msgs::bot_status_cmdResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::botcmd_msgs::bot_status_cmdResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::botcmd_msgs::bot_status_cmdResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::botcmd_msgs::bot_status_cmdResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c46eef13e83f9c7ad99dedda9f0f2fe0";
  }

  static const char* value(const ::botcmd_msgs::bot_status_cmdResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc46eef13e83f9c7aULL;
  static const uint64_t static_value2 = 0xd99dedda9f0f2fe0ULL;
};

template<class ContainerAllocator>
struct DataType< ::botcmd_msgs::bot_status_cmdResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "botcmd_msgs/bot_status_cmdResponse";
  }

  static const char* value(const ::botcmd_msgs::bot_status_cmdResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::botcmd_msgs::bot_status_cmdResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool result\n"
"time stamp\n"
"int16 result_Command \n"
"int8 status_code\n"
"int8 error_code\n"
"string data\n"
"\n"
;
  }

  static const char* value(const ::botcmd_msgs::bot_status_cmdResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::botcmd_msgs::bot_status_cmdResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
      stream.next(m.stamp);
      stream.next(m.result_Command);
      stream.next(m.status_code);
      stream.next(m.error_code);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct bot_status_cmdResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::botcmd_msgs::bot_status_cmdResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::botcmd_msgs::bot_status_cmdResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.result);
    s << indent << "stamp: ";
    Printer<ros::Time>::stream(s, indent + "  ", v.stamp);
    s << indent << "result_Command: ";
    Printer<int16_t>::stream(s, indent + "  ", v.result_Command);
    s << indent << "status_code: ";
    Printer<int8_t>::stream(s, indent + "  ", v.status_code);
    s << indent << "error_code: ";
    Printer<int8_t>::stream(s, indent + "  ", v.error_code);
    s << indent << "data: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.data);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BOTCMD_MSGS_MESSAGE_BOT_STATUS_CMDRESPONSE_H
