// Generated by gencpp from file botcmd_msgs/bot_mqtt_rawdata.msg
// DO NOT EDIT!


#ifndef BOTCMD_MSGS_MESSAGE_BOT_MQTT_RAWDATA_H
#define BOTCMD_MSGS_MESSAGE_BOT_MQTT_RAWDATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace botcmd_msgs
{
template <class ContainerAllocator>
struct bot_mqtt_rawdata_
{
  typedef bot_mqtt_rawdata_<ContainerAllocator> Type;

  bot_mqtt_rawdata_()
    : bImport_sensor(false)
    , bexport_sensor(false)  {
    }
  bot_mqtt_rawdata_(const ContainerAllocator& _alloc)
    : bImport_sensor(false)
    , bexport_sensor(false)  {
  (void)_alloc;
    }



   typedef uint8_t _bImport_sensor_type;
  _bImport_sensor_type bImport_sensor;

   typedef uint8_t _bexport_sensor_type;
  _bexport_sensor_type bexport_sensor;





  typedef boost::shared_ptr< ::botcmd_msgs::bot_mqtt_rawdata_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::botcmd_msgs::bot_mqtt_rawdata_<ContainerAllocator> const> ConstPtr;

}; // struct bot_mqtt_rawdata_

typedef ::botcmd_msgs::bot_mqtt_rawdata_<std::allocator<void> > bot_mqtt_rawdata;

typedef boost::shared_ptr< ::botcmd_msgs::bot_mqtt_rawdata > bot_mqtt_rawdataPtr;
typedef boost::shared_ptr< ::botcmd_msgs::bot_mqtt_rawdata const> bot_mqtt_rawdataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::botcmd_msgs::bot_mqtt_rawdata_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::botcmd_msgs::bot_mqtt_rawdata_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::botcmd_msgs::bot_mqtt_rawdata_<ContainerAllocator1> & lhs, const ::botcmd_msgs::bot_mqtt_rawdata_<ContainerAllocator2> & rhs)
{
  return lhs.bImport_sensor == rhs.bImport_sensor &&
    lhs.bexport_sensor == rhs.bexport_sensor;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::botcmd_msgs::bot_mqtt_rawdata_<ContainerAllocator1> & lhs, const ::botcmd_msgs::bot_mqtt_rawdata_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace botcmd_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::botcmd_msgs::bot_mqtt_rawdata_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::botcmd_msgs::bot_mqtt_rawdata_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::botcmd_msgs::bot_mqtt_rawdata_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::botcmd_msgs::bot_mqtt_rawdata_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::botcmd_msgs::bot_mqtt_rawdata_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::botcmd_msgs::bot_mqtt_rawdata_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::botcmd_msgs::bot_mqtt_rawdata_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3eaab3f40118d8034a925c7b353f23c2";
  }

  static const char* value(const ::botcmd_msgs::bot_mqtt_rawdata_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3eaab3f40118d803ULL;
  static const uint64_t static_value2 = 0x4a925c7b353f23c2ULL;
};

template<class ContainerAllocator>
struct DataType< ::botcmd_msgs::bot_mqtt_rawdata_<ContainerAllocator> >
{
  static const char* value()
  {
    return "botcmd_msgs/bot_mqtt_rawdata";
  }

  static const char* value(const ::botcmd_msgs::bot_mqtt_rawdata_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::botcmd_msgs::bot_mqtt_rawdata_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool   bImport_sensor\n"
"bool   bexport_sensor	\n"
;
  }

  static const char* value(const ::botcmd_msgs::bot_mqtt_rawdata_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::botcmd_msgs::bot_mqtt_rawdata_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.bImport_sensor);
      stream.next(m.bexport_sensor);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct bot_mqtt_rawdata_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::botcmd_msgs::bot_mqtt_rawdata_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::botcmd_msgs::bot_mqtt_rawdata_<ContainerAllocator>& v)
  {
    s << indent << "bImport_sensor: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.bImport_sensor);
    s << indent << "bexport_sensor: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.bexport_sensor);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BOTCMD_MSGS_MESSAGE_BOT_MQTT_RAWDATA_H
