string system_id 			
string alarm_id 		# module_no(3) + module alarm code(3)	
string alarm_code 		# same as alarm_id,preper for special requirement
string alarm_level 		# level of ararm: 1:alart 2:alarm	
string alarm_Desc_E 		# English description of alarm	
string alarm_Desc_TC 		# Traditional chinese description of alarm	
string alarm_Desc_SC 		# Sample chinese description of alarm
string alarm_version 		# version of alarm
string update_time 		# version time of alarm
