// Generated by gencpp from file robot_scheduling_msgs/pose_move_toGoal.msg
// DO NOT EDIT!


#ifndef ROBOT_SCHEDULING_MSGS_MESSAGE_POSE_MOVE_TOGOAL_H
#define ROBOT_SCHEDULING_MSGS_MESSAGE_POSE_MOVE_TOGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_scheduling_msgs
{
template <class ContainerAllocator>
struct pose_move_toGoal_
{
  typedef pose_move_toGoal_<ContainerAllocator> Type;

  pose_move_toGoal_()
    : pose_id()
    , frame_id()
    , command(0)
    , move_ac_name()  {
    }
  pose_move_toGoal_(const ContainerAllocator& _alloc)
    : pose_id(_alloc)
    , frame_id(_alloc)
    , command(0)
    , move_ac_name(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _pose_id_type;
  _pose_id_type pose_id;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _frame_id_type;
  _frame_id_type frame_id;

   typedef uint8_t _command_type;
  _command_type command;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _move_ac_name_type;
  _move_ac_name_type move_ac_name;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(CMD_MOVE)
  #undef CMD_MOVE
#endif
#if defined(_WIN32) && defined(CMD_STOP)
  #undef CMD_STOP
#endif

  enum {
    CMD_MOVE = 1u,
    CMD_STOP = 2u,
  };


  typedef boost::shared_ptr< ::robot_scheduling_msgs::pose_move_toGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_scheduling_msgs::pose_move_toGoal_<ContainerAllocator> const> ConstPtr;

}; // struct pose_move_toGoal_

typedef ::robot_scheduling_msgs::pose_move_toGoal_<std::allocator<void> > pose_move_toGoal;

typedef boost::shared_ptr< ::robot_scheduling_msgs::pose_move_toGoal > pose_move_toGoalPtr;
typedef boost::shared_ptr< ::robot_scheduling_msgs::pose_move_toGoal const> pose_move_toGoalConstPtr;

// constants requiring out of line definition

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_scheduling_msgs::pose_move_toGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_scheduling_msgs::pose_move_toGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_scheduling_msgs::pose_move_toGoal_<ContainerAllocator1> & lhs, const ::robot_scheduling_msgs::pose_move_toGoal_<ContainerAllocator2> & rhs)
{
  return lhs.pose_id == rhs.pose_id &&
    lhs.frame_id == rhs.frame_id &&
    lhs.command == rhs.command &&
    lhs.move_ac_name == rhs.move_ac_name;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_scheduling_msgs::pose_move_toGoal_<ContainerAllocator1> & lhs, const ::robot_scheduling_msgs::pose_move_toGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_scheduling_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::robot_scheduling_msgs::pose_move_toGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_scheduling_msgs::pose_move_toGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_scheduling_msgs::pose_move_toGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_scheduling_msgs::pose_move_toGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_scheduling_msgs::pose_move_toGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_scheduling_msgs::pose_move_toGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_scheduling_msgs::pose_move_toGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9eac014566724125d63c274f8dce5ded";
  }

  static const char* value(const ::robot_scheduling_msgs::pose_move_toGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9eac014566724125ULL;
  static const uint64_t static_value2 = 0xd63c274f8dce5dedULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_scheduling_msgs::pose_move_toGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_scheduling_msgs/pose_move_toGoal";
  }

  static const char* value(const ::robot_scheduling_msgs::pose_move_toGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_scheduling_msgs::pose_move_toGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Define the goal\n"
"string  pose_id\n"
"string frame_id\n"
"uint8 CMD_MOVE=1\n"
"uint8 CMD_STOP=2\n"
"#uint8 CMD_INTERRUPE=99\n"
"uint8  command\n"
"string move_ac_name\n"
;
  }

  static const char* value(const ::robot_scheduling_msgs::pose_move_toGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_scheduling_msgs::pose_move_toGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pose_id);
      stream.next(m.frame_id);
      stream.next(m.command);
      stream.next(m.move_ac_name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct pose_move_toGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_scheduling_msgs::pose_move_toGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_scheduling_msgs::pose_move_toGoal_<ContainerAllocator>& v)
  {
    s << indent << "pose_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.pose_id);
    s << indent << "frame_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.frame_id);
    s << indent << "command: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.command);
    s << indent << "move_ac_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.move_ac_name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_SCHEDULING_MSGS_MESSAGE_POSE_MOVE_TOGOAL_H
