// Generated by gencpp from file robot_scheduling_msgs/self_turn_toFeedback.msg
// DO NOT EDIT!


#ifndef ROBOT_SCHEDULING_MSGS_MESSAGE_SELF_TURN_TOFEEDBACK_H
#define ROBOT_SCHEDULING_MSGS_MESSAGE_SELF_TURN_TOFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_scheduling_msgs
{
template <class ContainerAllocator>
struct self_turn_toFeedback_
{
  typedef self_turn_toFeedback_<ContainerAllocator> Type;

  self_turn_toFeedback_()
    : delta_angle(0.0)
    , tuened(false)  {
    }
  self_turn_toFeedback_(const ContainerAllocator& _alloc)
    : delta_angle(0.0)
    , tuened(false)  {
  (void)_alloc;
    }



   typedef double _delta_angle_type;
  _delta_angle_type delta_angle;

   typedef uint8_t _tuened_type;
  _tuened_type tuened;





  typedef boost::shared_ptr< ::robot_scheduling_msgs::self_turn_toFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_scheduling_msgs::self_turn_toFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct self_turn_toFeedback_

typedef ::robot_scheduling_msgs::self_turn_toFeedback_<std::allocator<void> > self_turn_toFeedback;

typedef boost::shared_ptr< ::robot_scheduling_msgs::self_turn_toFeedback > self_turn_toFeedbackPtr;
typedef boost::shared_ptr< ::robot_scheduling_msgs::self_turn_toFeedback const> self_turn_toFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_scheduling_msgs::self_turn_toFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_scheduling_msgs::self_turn_toFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_scheduling_msgs::self_turn_toFeedback_<ContainerAllocator1> & lhs, const ::robot_scheduling_msgs::self_turn_toFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.delta_angle == rhs.delta_angle &&
    lhs.tuened == rhs.tuened;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_scheduling_msgs::self_turn_toFeedback_<ContainerAllocator1> & lhs, const ::robot_scheduling_msgs::self_turn_toFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_scheduling_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::robot_scheduling_msgs::self_turn_toFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_scheduling_msgs::self_turn_toFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_scheduling_msgs::self_turn_toFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_scheduling_msgs::self_turn_toFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_scheduling_msgs::self_turn_toFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_scheduling_msgs::self_turn_toFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_scheduling_msgs::self_turn_toFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "561e3716ece2d2003d0685c94f95b90f";
  }

  static const char* value(const ::robot_scheduling_msgs::self_turn_toFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x561e3716ece2d200ULL;
  static const uint64_t static_value2 = 0x3d0685c94f95b90fULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_scheduling_msgs::self_turn_toFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_scheduling_msgs/self_turn_toFeedback";
  }

  static const char* value(const ::robot_scheduling_msgs::self_turn_toFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_scheduling_msgs::self_turn_toFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Define a feedback message\n"
"float64 delta_angle\n"
"bool tuened\n"
"\n"
;
  }

  static const char* value(const ::robot_scheduling_msgs::self_turn_toFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_scheduling_msgs::self_turn_toFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.delta_angle);
      stream.next(m.tuened);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct self_turn_toFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_scheduling_msgs::self_turn_toFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_scheduling_msgs::self_turn_toFeedback_<ContainerAllocator>& v)
  {
    s << indent << "delta_angle: ";
    Printer<double>::stream(s, indent + "  ", v.delta_angle);
    s << indent << "tuened: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.tuened);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_SCHEDULING_MSGS_MESSAGE_SELF_TURN_TOFEEDBACK_H
