// Generated by gencpp from file robot_scheduling_msgs/undock_toFeedback.msg
// DO NOT EDIT!


#ifndef ROBOT_SCHEDULING_MSGS_MESSAGE_UNDOCK_TOFEEDBACK_H
#define ROBOT_SCHEDULING_MSGS_MESSAGE_UNDOCK_TOFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_scheduling_msgs
{
template <class ContainerAllocator>
struct undock_toFeedback_
{
  typedef undock_toFeedback_<ContainerAllocator> Type;

  undock_toFeedback_()
    : undocked(false)  {
    }
  undock_toFeedback_(const ContainerAllocator& _alloc)
    : undocked(false)  {
  (void)_alloc;
    }



   typedef uint8_t _undocked_type;
  _undocked_type undocked;





  typedef boost::shared_ptr< ::robot_scheduling_msgs::undock_toFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_scheduling_msgs::undock_toFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct undock_toFeedback_

typedef ::robot_scheduling_msgs::undock_toFeedback_<std::allocator<void> > undock_toFeedback;

typedef boost::shared_ptr< ::robot_scheduling_msgs::undock_toFeedback > undock_toFeedbackPtr;
typedef boost::shared_ptr< ::robot_scheduling_msgs::undock_toFeedback const> undock_toFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_scheduling_msgs::undock_toFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_scheduling_msgs::undock_toFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_scheduling_msgs::undock_toFeedback_<ContainerAllocator1> & lhs, const ::robot_scheduling_msgs::undock_toFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.undocked == rhs.undocked;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_scheduling_msgs::undock_toFeedback_<ContainerAllocator1> & lhs, const ::robot_scheduling_msgs::undock_toFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_scheduling_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::robot_scheduling_msgs::undock_toFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_scheduling_msgs::undock_toFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_scheduling_msgs::undock_toFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_scheduling_msgs::undock_toFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_scheduling_msgs::undock_toFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_scheduling_msgs::undock_toFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_scheduling_msgs::undock_toFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "26f25fb4c0c6a6805fac81b37bb7b9c9";
  }

  static const char* value(const ::robot_scheduling_msgs::undock_toFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x26f25fb4c0c6a680ULL;
  static const uint64_t static_value2 = 0x5fac81b37bb7b9c9ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_scheduling_msgs::undock_toFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_scheduling_msgs/undock_toFeedback";
  }

  static const char* value(const ::robot_scheduling_msgs::undock_toFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_scheduling_msgs::undock_toFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Define a feedback message\n"
"bool undocked\n"
"\n"
;
  }

  static const char* value(const ::robot_scheduling_msgs::undock_toFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_scheduling_msgs::undock_toFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.undocked);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct undock_toFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_scheduling_msgs::undock_toFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_scheduling_msgs::undock_toFeedback_<ContainerAllocator>& v)
  {
    s << indent << "undocked: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.undocked);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_SCHEDULING_MSGS_MESSAGE_UNDOCK_TOFEEDBACK_H
