// Auto-generated. Do not edit!

// (in-package robot_scheduling_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class robot_interface_proc_upperResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.result = null;
      this.result_state = null;
      this.result_data = null;
    }
    else {
      if (initObj.hasOwnProperty('result')) {
        this.result = initObj.result
      }
      else {
        this.result = false;
      }
      if (initObj.hasOwnProperty('result_state')) {
        this.result_state = initObj.result_state
      }
      else {
        this.result_state = 0;
      }
      if (initObj.hasOwnProperty('result_data')) {
        this.result_data = initObj.result_data
      }
      else {
        this.result_data = '';
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type robot_interface_proc_upperResult
    // Serialize message field [result]
    bufferOffset = _serializer.bool(obj.result, buffer, bufferOffset);
    // Serialize message field [result_state]
    bufferOffset = _serializer.uint8(obj.result_state, buffer, bufferOffset);
    // Serialize message field [result_data]
    bufferOffset = _serializer.string(obj.result_data, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type robot_interface_proc_upperResult
    let len;
    let data = new robot_interface_proc_upperResult(null);
    // Deserialize message field [result]
    data.result = _deserializer.bool(buffer, bufferOffset);
    // Deserialize message field [result_state]
    data.result_state = _deserializer.uint8(buffer, bufferOffset);
    // Deserialize message field [result_data]
    data.result_data = _deserializer.string(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += object.result_data.length;
    return length + 6;
  }

  static datatype() {
    // Returns string type for a message object
    return 'robot_scheduling_msgs/robot_interface_proc_upperResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return 'df1f5eb73492eb1c6b87f4934795b18c';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Define the result
    bool result
    uint8 OK=1
    uint8 NOT_OK=2
    uint8 TIMED_OUT=3
    uint8 OUT_OF_TIMES=4
    uint8 PASS=5
    uint8 result_state
    string result_data
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new robot_interface_proc_upperResult(null);
    if (msg.result !== undefined) {
      resolved.result = msg.result;
    }
    else {
      resolved.result = false
    }

    if (msg.result_state !== undefined) {
      resolved.result_state = msg.result_state;
    }
    else {
      resolved.result_state = 0
    }

    if (msg.result_data !== undefined) {
      resolved.result_data = msg.result_data;
    }
    else {
      resolved.result_data = ''
    }

    return resolved;
    }
};

// Constants for message
robot_interface_proc_upperResult.Constants = {
  OK: 1,
  NOT_OK: 2,
  TIMED_OUT: 3,
  OUT_OF_TIMES: 4,
  PASS: 5,
}

module.exports = robot_interface_proc_upperResult;
