// Auto-generated. Do not edit!

// (in-package robot_scheduling_msgs.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class worksheetrunFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.current_index = null;
      this.current_function = null;
    }
    else {
      if (initObj.hasOwnProperty('current_index')) {
        this.current_index = initObj.current_index
      }
      else {
        this.current_index = 0;
      }
      if (initObj.hasOwnProperty('current_function')) {
        this.current_function = initObj.current_function
      }
      else {
        this.current_function = 0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type worksheetrunFeedback
    // Serialize message field [current_index]
    bufferOffset = _serializer.uint8(obj.current_index, buffer, bufferOffset);
    // Serialize message field [current_function]
    bufferOffset = _serializer.uint8(obj.current_function, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type worksheetrunFeedback
    let len;
    let data = new worksheetrunFeedback(null);
    // Deserialize message field [current_index]
    data.current_index = _deserializer.uint8(buffer, bufferOffset);
    // Deserialize message field [current_function]
    data.current_function = _deserializer.uint8(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    return 2;
  }

  static datatype() {
    // Returns string type for a message object
    return 'robot_scheduling_msgs/worksheetrunFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '1c061f430842d65f8354d802c6aced9a';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # Define a feedback message
    uint8 current_index
    uint8 current_function
    
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new worksheetrunFeedback(null);
    if (msg.current_index !== undefined) {
      resolved.current_index = msg.current_index;
    }
    else {
      resolved.current_index = 0
    }

    if (msg.current_function !== undefined) {
      resolved.current_function = msg.current_function;
    }
    else {
      resolved.current_function = 0
    }

    return resolved;
    }
};

module.exports = worksheetrunFeedback;
