// Generated by gencpp from file cellctrl_control_msgs/cell_battery_remain.msg
// DO NOT EDIT!


#ifndef CELLCTRL_CONTROL_MSGS_MESSAGE_CELL_BATTERY_REMAIN_H
#define CELLCTRL_CONTROL_MSGS_MESSAGE_CELL_BATTERY_REMAIN_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cellctrl_control_msgs
{
template <class ContainerAllocator>
struct cell_battery_remain_
{
  typedef cell_battery_remain_<ContainerAllocator> Type;

  cell_battery_remain_()
    : primary_id()
    , foreign_key()
    , unique_code()
    , remain_name()
    , remain_ser(0)
    , ctrl_seg_capacity(0.0)
    , ctrl_seg_efficiency(0.0)
    , update_time()  {
    }
  cell_battery_remain_(const ContainerAllocator& _alloc)
    : primary_id(_alloc)
    , foreign_key(_alloc)
    , unique_code(_alloc)
    , remain_name(_alloc)
    , remain_ser(0)
    , ctrl_seg_capacity(0.0)
    , ctrl_seg_efficiency(0.0)
    , update_time(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _primary_id_type;
  _primary_id_type primary_id;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _foreign_key_type;
  _foreign_key_type foreign_key;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _unique_code_type;
  _unique_code_type unique_code;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _remain_name_type;
  _remain_name_type remain_name;

   typedef uint8_t _remain_ser_type;
  _remain_ser_type remain_ser;

   typedef float _ctrl_seg_capacity_type;
  _ctrl_seg_capacity_type ctrl_seg_capacity;

   typedef float _ctrl_seg_efficiency_type;
  _ctrl_seg_efficiency_type ctrl_seg_efficiency;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _update_time_type;
  _update_time_type update_time;





  typedef boost::shared_ptr< ::cellctrl_control_msgs::cell_battery_remain_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cellctrl_control_msgs::cell_battery_remain_<ContainerAllocator> const> ConstPtr;

}; // struct cell_battery_remain_

typedef ::cellctrl_control_msgs::cell_battery_remain_<std::allocator<void> > cell_battery_remain;

typedef boost::shared_ptr< ::cellctrl_control_msgs::cell_battery_remain > cell_battery_remainPtr;
typedef boost::shared_ptr< ::cellctrl_control_msgs::cell_battery_remain const> cell_battery_remainConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cellctrl_control_msgs::cell_battery_remain_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cellctrl_control_msgs::cell_battery_remain_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::cellctrl_control_msgs::cell_battery_remain_<ContainerAllocator1> & lhs, const ::cellctrl_control_msgs::cell_battery_remain_<ContainerAllocator2> & rhs)
{
  return lhs.primary_id == rhs.primary_id &&
    lhs.foreign_key == rhs.foreign_key &&
    lhs.unique_code == rhs.unique_code &&
    lhs.remain_name == rhs.remain_name &&
    lhs.remain_ser == rhs.remain_ser &&
    lhs.ctrl_seg_capacity == rhs.ctrl_seg_capacity &&
    lhs.ctrl_seg_efficiency == rhs.ctrl_seg_efficiency &&
    lhs.update_time == rhs.update_time;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::cellctrl_control_msgs::cell_battery_remain_<ContainerAllocator1> & lhs, const ::cellctrl_control_msgs::cell_battery_remain_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace cellctrl_control_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::cellctrl_control_msgs::cell_battery_remain_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cellctrl_control_msgs::cell_battery_remain_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cellctrl_control_msgs::cell_battery_remain_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cellctrl_control_msgs::cell_battery_remain_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cellctrl_control_msgs::cell_battery_remain_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cellctrl_control_msgs::cell_battery_remain_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cellctrl_control_msgs::cell_battery_remain_<ContainerAllocator> >
{
  static const char* value()
  {
    return "abd07889143305d736d12035e783fbc9";
  }

  static const char* value(const ::cellctrl_control_msgs::cell_battery_remain_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xabd07889143305d7ULL;
  static const uint64_t static_value2 = 0x36d12035e783fbc9ULL;
};

template<class ContainerAllocator>
struct DataType< ::cellctrl_control_msgs::cell_battery_remain_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cellctrl_control_msgs/cell_battery_remain";
  }

  static const char* value(const ::cellctrl_control_msgs::cell_battery_remain_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cellctrl_control_msgs::cell_battery_remain_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string primary_id			# must-have,UUID : primary_key(system_id)		\n"
"string foreign_key\n"
"string unique_code 		        # must-have,UNIQUE INDEX	\n"
"string remain_name	\n"
"uint8 remain_ser	   \n"
"float32 ctrl_seg_capacity 		 \n"
"float32 ctrl_seg_efficiency \n"
"string update_time			# must-have 		 \n"
;
  }

  static const char* value(const ::cellctrl_control_msgs::cell_battery_remain_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cellctrl_control_msgs::cell_battery_remain_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.primary_id);
      stream.next(m.foreign_key);
      stream.next(m.unique_code);
      stream.next(m.remain_name);
      stream.next(m.remain_ser);
      stream.next(m.ctrl_seg_capacity);
      stream.next(m.ctrl_seg_efficiency);
      stream.next(m.update_time);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct cell_battery_remain_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cellctrl_control_msgs::cell_battery_remain_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cellctrl_control_msgs::cell_battery_remain_<ContainerAllocator>& v)
  {
    s << indent << "primary_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.primary_id);
    s << indent << "foreign_key: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.foreign_key);
    s << indent << "unique_code: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.unique_code);
    s << indent << "remain_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.remain_name);
    s << indent << "remain_ser: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.remain_ser);
    s << indent << "ctrl_seg_capacity: ";
    Printer<float>::stream(s, indent + "  ", v.ctrl_seg_capacity);
    s << indent << "ctrl_seg_efficiency: ";
    Printer<float>::stream(s, indent + "  ", v.ctrl_seg_efficiency);
    s << indent << "update_time: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.update_time);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CELLCTRL_CONTROL_MSGS_MESSAGE_CELL_BATTERY_REMAIN_H
