// Generated by gencpp from file cellctrl_control_msgs/cell_work_ordergoods_cmd.msg
// DO NOT EDIT!


#ifndef CELLCTRL_CONTROL_MSGS_MESSAGE_CELL_WORK_ORDERGOODS_CMD_H
#define CELLCTRL_CONTROL_MSGS_MESSAGE_CELL_WORK_ORDERGOODS_CMD_H

#include <ros/service_traits.h>


#include <cellctrl_control_msgs/cell_work_ordergoods_cmdRequest.h>
#include <cellctrl_control_msgs/cell_work_ordergoods_cmdResponse.h>


namespace cellctrl_control_msgs
{

struct cell_work_ordergoods_cmd
{

typedef cell_work_ordergoods_cmdRequest Request;
typedef cell_work_ordergoods_cmdResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct cell_work_ordergoods_cmd
} // namespace cellctrl_control_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::cellctrl_control_msgs::cell_work_ordergoods_cmd > {
  static const char* value()
  {
    return "a39af5e267cfcbbc4899b66e549fff7f";
  }

  static const char* value(const ::cellctrl_control_msgs::cell_work_ordergoods_cmd&) { return value(); }
};

template<>
struct DataType< ::cellctrl_control_msgs::cell_work_ordergoods_cmd > {
  static const char* value()
  {
    return "cellctrl_control_msgs/cell_work_ordergoods_cmd";
  }

  static const char* value(const ::cellctrl_control_msgs::cell_work_ordergoods_cmd&) { return value(); }
};


// service_traits::MD5Sum< ::cellctrl_control_msgs::cell_work_ordergoods_cmdRequest> should match
// service_traits::MD5Sum< ::cellctrl_control_msgs::cell_work_ordergoods_cmd >
template<>
struct MD5Sum< ::cellctrl_control_msgs::cell_work_ordergoods_cmdRequest>
{
  static const char* value()
  {
    return MD5Sum< ::cellctrl_control_msgs::cell_work_ordergoods_cmd >::value();
  }
  static const char* value(const ::cellctrl_control_msgs::cell_work_ordergoods_cmdRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::cellctrl_control_msgs::cell_work_ordergoods_cmdRequest> should match
// service_traits::DataType< ::cellctrl_control_msgs::cell_work_ordergoods_cmd >
template<>
struct DataType< ::cellctrl_control_msgs::cell_work_ordergoods_cmdRequest>
{
  static const char* value()
  {
    return DataType< ::cellctrl_control_msgs::cell_work_ordergoods_cmd >::value();
  }
  static const char* value(const ::cellctrl_control_msgs::cell_work_ordergoods_cmdRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::cellctrl_control_msgs::cell_work_ordergoods_cmdResponse> should match
// service_traits::MD5Sum< ::cellctrl_control_msgs::cell_work_ordergoods_cmd >
template<>
struct MD5Sum< ::cellctrl_control_msgs::cell_work_ordergoods_cmdResponse>
{
  static const char* value()
  {
    return MD5Sum< ::cellctrl_control_msgs::cell_work_ordergoods_cmd >::value();
  }
  static const char* value(const ::cellctrl_control_msgs::cell_work_ordergoods_cmdResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::cellctrl_control_msgs::cell_work_ordergoods_cmdResponse> should match
// service_traits::DataType< ::cellctrl_control_msgs::cell_work_ordergoods_cmd >
template<>
struct DataType< ::cellctrl_control_msgs::cell_work_ordergoods_cmdResponse>
{
  static const char* value()
  {
    return DataType< ::cellctrl_control_msgs::cell_work_ordergoods_cmd >::value();
  }
  static const char* value(const ::cellctrl_control_msgs::cell_work_ordergoods_cmdResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CELLCTRL_CONTROL_MSGS_MESSAGE_CELL_WORK_ORDERGOODS_CMD_H
