## USB port
port: /dev/imu
frame_id: imu_link
#port: /dev/ttyACM2

##### Calibration ####
### accelerometer
accel_x_min: -250.0
accel_x_max: 250.0
accel_y_min: -250.0
accel_y_max: 250.0
accel_z_min: -250.0
accel_z_max: 250.0

### magnetometer
# standard calibration
magn_x_min: -102.03
magn_x_max: -58.51
magn_y_min: -838.71
magn_y_max: -795.2
magn_z_min: -1201.80
magn_z_max: -1159.79

# extended calibration
calibration_magn_use_extended: false
magn_ellipsoid_center: [0, 0, 0]
magn_ellipsoid_transform: [[0, 0, 0], [0, 0, 0], [0, 0, 0]]

# AHRS to robot calibration
imu_yaw_calibration: 0.0

### gyroscope
gyro_average_offset_x: -0.03
gyro_average_offset_y: -0.01
gyro_average_offset_z: -0.01
